import React from 'react';
import Component from 'react-pure-render/component';
import {connect} from 'react-redux';
import Modal from '../components/modal';
import FlexModalWrapper from 'react-modal-wrapper';
import Signin from './signin';
import Signup from './signup';

const mapStateToProps = (state) => ({
  user: state.user
});

class Account extends Component {

  static propTypes = {
    user: React.PropTypes.object.isRequired
  };

  render() {
    const signInModal = <b><a href="#">Sign in</a></b>;
    return (
      <div style={{float: 'left', marginRight: '13px', textAlign: 'right'}}>
        <a href="#" title="This username was autogenerated. You should sign in!" style={{color: 'red'}}>
          {this.props.user.userId}
        </a>
        <br />

        <FlexModalWrapper className="modal" closeOnEsc closeOnOutsideClick openByClickOn={signInModal}>
          <Modal>
            <h2>Hey, stay with us!</h2>
            <p>
              <i>{this.props.user.userId}</i> is autogenerated. You should <strong>SIGN UP</strong><br /> and get a long term
              account with password.
            </p>

            {this.props.user.accountAdded ?
              <div style={{textAlign: 'center', color: 'darkred'}}>Account added! Sign in now!</div> :
              <Signup />
            }
            <hr />
            <p>Or <strong>SIGN IN</strong> if you already have a long term account.</p>
            <Signin />
            <hr />
          </Modal>
        </FlexModalWrapper>
      </div>
    );
  }
}

export default connect(mapStateToProps)(Account);
